services:
  - type: web
    name: lm-passo
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "3000"
